/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.DepModel#getDepmodels <em>Depmodels</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getDepModel()
 * @model
 * @generated
 */
public interface DepModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Depmodels</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.depModel.abstractModelDec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Depmodels</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depmodels</em>' containment reference list.
   * @see hu.bme.mit.depModel.DepModelPackage#getDepModel_Depmodels()
   * @model containment="true"
   * @generated
   */
  EList<abstractModelDec> getDepmodels();

} // DepModel
