/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>In Port</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getInPort()
 * @model
 * @generated
 */
public interface InPort extends Port
{
} // InPort
