/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit;

import hu.bme.mit.AbstractErrorModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ErrorModelRuntimeModule extends AbstractErrorModelRuntimeModule {
}
