/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.tests

import com.google.inject.Inject
import hu.bme.mit.errorModel.ErrorModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ErrorModelInjectorProvider)
class ErrorModelParsingTest{

	@Inject
	ParseHelper<ErrorModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
