/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Conn Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.componentModel.CompConnDec#getSourceComp <em>Source Comp</em>}</li>
 *   <li>{@link hu.bme.mit.componentModel.CompConnDec#getSourcePort <em>Source Port</em>}</li>
 *   <li>{@link hu.bme.mit.componentModel.CompConnDec#getTargetComp <em>Target Comp</em>}</li>
 *   <li>{@link hu.bme.mit.componentModel.CompConnDec#getTargetPort <em>Target Port</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.componentModel.ComponentModelPackage#getCompConnDec()
 * @model
 * @generated
 */
public interface CompConnDec extends AbstractFeatures
{
  /**
   * Returns the value of the '<em><b>Source Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Comp</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Comp</em>' reference.
   * @see #setSourceComp(ComponentImpl)
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getCompConnDec_SourceComp()
   * @model
   * @generated
   */
  ComponentImpl getSourceComp();

  /**
   * Sets the value of the '{@link hu.bme.mit.componentModel.CompConnDec#getSourceComp <em>Source Comp</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Comp</em>' reference.
   * @see #getSourceComp()
   * @generated
   */
  void setSourceComp(ComponentImpl value);

  /**
   * Returns the value of the '<em><b>Source Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Port</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Port</em>' reference.
   * @see #setSourcePort(OutPort)
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getCompConnDec_SourcePort()
   * @model
   * @generated
   */
  OutPort getSourcePort();

  /**
   * Sets the value of the '{@link hu.bme.mit.componentModel.CompConnDec#getSourcePort <em>Source Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Port</em>' reference.
   * @see #getSourcePort()
   * @generated
   */
  void setSourcePort(OutPort value);

  /**
   * Returns the value of the '<em><b>Target Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Comp</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Comp</em>' reference.
   * @see #setTargetComp(ComponentImpl)
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getCompConnDec_TargetComp()
   * @model
   * @generated
   */
  ComponentImpl getTargetComp();

  /**
   * Sets the value of the '{@link hu.bme.mit.componentModel.CompConnDec#getTargetComp <em>Target Comp</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Comp</em>' reference.
   * @see #getTargetComp()
   * @generated
   */
  void setTargetComp(ComponentImpl value);

  /**
   * Returns the value of the '<em><b>Target Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Port</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Port</em>' reference.
   * @see #setTargetPort(InPort)
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getCompConnDec_TargetPort()
   * @model
   * @generated
   */
  InPort getTargetPort();

  /**
   * Sets the value of the '{@link hu.bme.mit.componentModel.CompConnDec#getTargetPort <em>Target Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Port</em>' reference.
   * @see #getTargetPort()
   * @generated
   */
  void setTargetPort(InPort value);

} // CompConnDec
