/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EModel Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.componentModel.ComponentModelPackage#getEModelElement()
 * @model
 * @generated
 */
public interface EModelElement extends EObject
{
} // EModelElement
