/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.componentModel.TransitionDec#getNameEventDec <em>Name Event Dec</em>}</li>
 *   <li>{@link hu.bme.mit.componentModel.TransitionDec#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.componentModel.ComponentModelPackage#getTransitionDec()
 * @model
 * @generated
 */
public interface TransitionDec extends EModelElement
{
  /**
   * Returns the value of the '<em><b>Name Event Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Event Dec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Event Dec</em>' attribute.
   * @see #setNameEventDec(String)
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getTransitionDec_NameEventDec()
   * @model
   * @generated
   */
  String getNameEventDec();

  /**
   * Sets the value of the '{@link hu.bme.mit.componentModel.TransitionDec#getNameEventDec <em>Name Event Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Event Dec</em>' attribute.
   * @see #getNameEventDec()
   * @generated
   */
  void setNameEventDec(String value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.componentModel.TransitionFeatureDec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see hu.bme.mit.componentModel.ComponentModelPackage#getTransitionDec_Features()
   * @model containment="true"
   * @generated
   */
  EList<TransitionFeatureDec> getFeatures();

} // TransitionDec
