/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hu.bme.mit.errorModel.ErrorModelFactory
 * @model kind="package"
 * @generated
 */
public interface ErrorModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "errorModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.bme.hu/mit/ErrorModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "errorModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ErrorModelPackage eINSTANCE = hu.bme.mit.errorModel.impl.ErrorModelPackageImpl.init();

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.ErrorModelImpl <em>Error Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.ErrorModelImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getErrorModel()
   * @generated
   */
  int ERROR_MODEL = 0;

  /**
   * The feature id for the '<em><b>Abstract Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL__ABSTRACT_ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Error Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.ErrorImpl <em>Error</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.ErrorImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getError()
   * @generated
   */
  int ERROR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR__NAME = 0;

  /**
   * The number of structural features of the '<em>Error</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EPropagationDecImpl <em>EPropagation Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EPropagationDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEPropagationDec()
   * @generated
   */
  int EPROPAGATION_DEC = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC__NAME = ERROR__NAME;

  /**
   * The feature id for the '<em><b>Source Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC__SOURCE_MODEL = ERROR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source Prop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC__SOURCE_PROP = ERROR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC__TARGET_MODEL = ERROR_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target Prop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC__TARGET_PROP = ERROR_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>EPropagation Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPROPAGATION_DEC_FEATURE_COUNT = ERROR_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EModelDecImpl <em>EModel Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EModelDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEModelDec()
   * @generated
   */
  int EMODEL_DEC = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMODEL_DEC__NAME = ERROR__NAME;

  /**
   * The feature id for the '<em><b>Emodel Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMODEL_DEC__EMODEL_ELEMENTS = ERROR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>EModel Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMODEL_DEC_FEATURE_COUNT = ERROR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EModelElementImpl <em>EModel Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EModelElementImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEModelElement()
   * @generated
   */
  int EMODEL_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMODEL_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>EModel Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMODEL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.OuterPropagationImpl <em>Outer Propagation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.OuterPropagationImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getOuterPropagation()
   * @generated
   */
  int OUTER_PROPAGATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTER_PROPAGATION__NAME = EMODEL_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Outer Propagation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTER_PROPAGATION_FEATURE_COUNT = EMODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.InPropDecImpl <em>In Prop Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.InPropDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getInPropDec()
   * @generated
   */
  int IN_PROP_DEC = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_PROP_DEC__NAME = OUTER_PROPAGATION__NAME;

  /**
   * The feature id for the '<em><b>Affected State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_PROP_DEC__AFFECTED_STATE = OUTER_PROPAGATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>In Prop Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_PROP_DEC_FEATURE_COUNT = OUTER_PROPAGATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.OutPropDecImpl <em>Out Prop Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.OutPropDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getOutPropDec()
   * @generated
   */
  int OUT_PROP_DEC = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_PROP_DEC__NAME = OUTER_PROPAGATION__NAME;

  /**
   * The feature id for the '<em><b>From State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_PROP_DEC__FROM_STATE = OUTER_PROPAGATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Out Prop Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_PROP_DEC_FEATURE_COUNT = OUTER_PROPAGATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.StateDecImpl <em>State Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.StateDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getStateDec()
   * @generated
   */
  int STATE_DEC = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEC__NAME = EMODEL_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>State Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEC_FEATURE_COUNT = EMODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EventDecImpl <em>Event Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EventDecImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventDec()
   * @generated
   */
  int EVENT_DEC = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_DEC__NAME = EMODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Event Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_DEC__EVENT_FEATURES = EMODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Event Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_DEC_FEATURE_COUNT = EMODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EventFeatureImpl <em>Event Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EventFeatureImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventFeature()
   * @generated
   */
  int EVENT_FEATURE = 10;

  /**
   * The number of structural features of the '<em>Event Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.errorModel.impl.EventStateImpl <em>Event State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.errorModel.impl.EventStateImpl
   * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventState()
   * @generated
   */
  int EVENT_STATE = 11;

  /**
   * The feature id for the '<em><b>Source State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_STATE__SOURCE_STATE = EVENT_FEATURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_STATE__TARGET_STATE = EVENT_FEATURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Event State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_STATE_FEATURE_COUNT = EVENT_FEATURE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.ErrorModel <em>Error Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Model</em>'.
   * @see hu.bme.mit.errorModel.ErrorModel
   * @generated
   */
  EClass getErrorModel();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.errorModel.ErrorModel#getAbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Abstract Element</em>'.
   * @see hu.bme.mit.errorModel.ErrorModel#getAbstractElement()
   * @see #getErrorModel()
   * @generated
   */
  EReference getErrorModel_AbstractElement();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.Error <em>Error</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error</em>'.
   * @see hu.bme.mit.errorModel.Error
   * @generated
   */
  EClass getError();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.errorModel.Error#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.errorModel.Error#getName()
   * @see #getError()
   * @generated
   */
  EAttribute getError_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EPropagationDec <em>EPropagation Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EPropagation Dec</em>'.
   * @see hu.bme.mit.errorModel.EPropagationDec
   * @generated
   */
  EClass getEPropagationDec();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EPropagationDec#getSourceModel <em>Source Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Model</em>'.
   * @see hu.bme.mit.errorModel.EPropagationDec#getSourceModel()
   * @see #getEPropagationDec()
   * @generated
   */
  EReference getEPropagationDec_SourceModel();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EPropagationDec#getSourceProp <em>Source Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Prop</em>'.
   * @see hu.bme.mit.errorModel.EPropagationDec#getSourceProp()
   * @see #getEPropagationDec()
   * @generated
   */
  EReference getEPropagationDec_SourceProp();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EPropagationDec#getTargetModel <em>Target Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Model</em>'.
   * @see hu.bme.mit.errorModel.EPropagationDec#getTargetModel()
   * @see #getEPropagationDec()
   * @generated
   */
  EReference getEPropagationDec_TargetModel();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EPropagationDec#getTargetProp <em>Target Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Prop</em>'.
   * @see hu.bme.mit.errorModel.EPropagationDec#getTargetProp()
   * @see #getEPropagationDec()
   * @generated
   */
  EReference getEPropagationDec_TargetProp();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EModelDec <em>EModel Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EModel Dec</em>'.
   * @see hu.bme.mit.errorModel.EModelDec
   * @generated
   */
  EClass getEModelDec();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.errorModel.EModelDec#getEmodelElements <em>Emodel Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Emodel Elements</em>'.
   * @see hu.bme.mit.errorModel.EModelDec#getEmodelElements()
   * @see #getEModelDec()
   * @generated
   */
  EReference getEModelDec_EmodelElements();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EModelElement <em>EModel Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EModel Element</em>'.
   * @see hu.bme.mit.errorModel.EModelElement
   * @generated
   */
  EClass getEModelElement();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.errorModel.EModelElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.errorModel.EModelElement#getName()
   * @see #getEModelElement()
   * @generated
   */
  EAttribute getEModelElement_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.OuterPropagation <em>Outer Propagation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outer Propagation</em>'.
   * @see hu.bme.mit.errorModel.OuterPropagation
   * @generated
   */
  EClass getOuterPropagation();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.InPropDec <em>In Prop Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>In Prop Dec</em>'.
   * @see hu.bme.mit.errorModel.InPropDec
   * @generated
   */
  EClass getInPropDec();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.InPropDec#getAffectedState <em>Affected State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Affected State</em>'.
   * @see hu.bme.mit.errorModel.InPropDec#getAffectedState()
   * @see #getInPropDec()
   * @generated
   */
  EReference getInPropDec_AffectedState();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.OutPropDec <em>Out Prop Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Out Prop Dec</em>'.
   * @see hu.bme.mit.errorModel.OutPropDec
   * @generated
   */
  EClass getOutPropDec();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.OutPropDec#getFromState <em>From State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From State</em>'.
   * @see hu.bme.mit.errorModel.OutPropDec#getFromState()
   * @see #getOutPropDec()
   * @generated
   */
  EReference getOutPropDec_FromState();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.StateDec <em>State Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Dec</em>'.
   * @see hu.bme.mit.errorModel.StateDec
   * @generated
   */
  EClass getStateDec();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EventDec <em>Event Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Dec</em>'.
   * @see hu.bme.mit.errorModel.EventDec
   * @generated
   */
  EClass getEventDec();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.errorModel.EventDec#getEventFeatures <em>Event Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Event Features</em>'.
   * @see hu.bme.mit.errorModel.EventDec#getEventFeatures()
   * @see #getEventDec()
   * @generated
   */
  EReference getEventDec_EventFeatures();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EventFeature <em>Event Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Feature</em>'.
   * @see hu.bme.mit.errorModel.EventFeature
   * @generated
   */
  EClass getEventFeature();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.errorModel.EventState <em>Event State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event State</em>'.
   * @see hu.bme.mit.errorModel.EventState
   * @generated
   */
  EClass getEventState();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EventState#getSourceState <em>Source State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source State</em>'.
   * @see hu.bme.mit.errorModel.EventState#getSourceState()
   * @see #getEventState()
   * @generated
   */
  EReference getEventState_SourceState();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.errorModel.EventState#getTargetState <em>Target State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target State</em>'.
   * @see hu.bme.mit.errorModel.EventState#getTargetState()
   * @see #getEventState()
   * @generated
   */
  EReference getEventState_TargetState();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ErrorModelFactory getErrorModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.ErrorModelImpl <em>Error Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.ErrorModelImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getErrorModel()
     * @generated
     */
    EClass ERROR_MODEL = eINSTANCE.getErrorModel();

    /**
     * The meta object literal for the '<em><b>Abstract Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ERROR_MODEL__ABSTRACT_ELEMENT = eINSTANCE.getErrorModel_AbstractElement();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.ErrorImpl <em>Error</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.ErrorImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getError()
     * @generated
     */
    EClass ERROR = eINSTANCE.getError();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ERROR__NAME = eINSTANCE.getError_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EPropagationDecImpl <em>EPropagation Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EPropagationDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEPropagationDec()
     * @generated
     */
    EClass EPROPAGATION_DEC = eINSTANCE.getEPropagationDec();

    /**
     * The meta object literal for the '<em><b>Source Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EPROPAGATION_DEC__SOURCE_MODEL = eINSTANCE.getEPropagationDec_SourceModel();

    /**
     * The meta object literal for the '<em><b>Source Prop</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EPROPAGATION_DEC__SOURCE_PROP = eINSTANCE.getEPropagationDec_SourceProp();

    /**
     * The meta object literal for the '<em><b>Target Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EPROPAGATION_DEC__TARGET_MODEL = eINSTANCE.getEPropagationDec_TargetModel();

    /**
     * The meta object literal for the '<em><b>Target Prop</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EPROPAGATION_DEC__TARGET_PROP = eINSTANCE.getEPropagationDec_TargetProp();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EModelDecImpl <em>EModel Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EModelDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEModelDec()
     * @generated
     */
    EClass EMODEL_DEC = eINSTANCE.getEModelDec();

    /**
     * The meta object literal for the '<em><b>Emodel Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMODEL_DEC__EMODEL_ELEMENTS = eINSTANCE.getEModelDec_EmodelElements();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EModelElementImpl <em>EModel Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EModelElementImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEModelElement()
     * @generated
     */
    EClass EMODEL_ELEMENT = eINSTANCE.getEModelElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMODEL_ELEMENT__NAME = eINSTANCE.getEModelElement_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.OuterPropagationImpl <em>Outer Propagation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.OuterPropagationImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getOuterPropagation()
     * @generated
     */
    EClass OUTER_PROPAGATION = eINSTANCE.getOuterPropagation();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.InPropDecImpl <em>In Prop Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.InPropDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getInPropDec()
     * @generated
     */
    EClass IN_PROP_DEC = eINSTANCE.getInPropDec();

    /**
     * The meta object literal for the '<em><b>Affected State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IN_PROP_DEC__AFFECTED_STATE = eINSTANCE.getInPropDec_AffectedState();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.OutPropDecImpl <em>Out Prop Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.OutPropDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getOutPropDec()
     * @generated
     */
    EClass OUT_PROP_DEC = eINSTANCE.getOutPropDec();

    /**
     * The meta object literal for the '<em><b>From State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUT_PROP_DEC__FROM_STATE = eINSTANCE.getOutPropDec_FromState();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.StateDecImpl <em>State Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.StateDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getStateDec()
     * @generated
     */
    EClass STATE_DEC = eINSTANCE.getStateDec();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EventDecImpl <em>Event Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EventDecImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventDec()
     * @generated
     */
    EClass EVENT_DEC = eINSTANCE.getEventDec();

    /**
     * The meta object literal for the '<em><b>Event Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_DEC__EVENT_FEATURES = eINSTANCE.getEventDec_EventFeatures();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EventFeatureImpl <em>Event Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EventFeatureImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventFeature()
     * @generated
     */
    EClass EVENT_FEATURE = eINSTANCE.getEventFeature();

    /**
     * The meta object literal for the '{@link hu.bme.mit.errorModel.impl.EventStateImpl <em>Event State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.errorModel.impl.EventStateImpl
     * @see hu.bme.mit.errorModel.impl.ErrorModelPackageImpl#getEventState()
     * @generated
     */
    EClass EVENT_STATE = eINSTANCE.getEventState();

    /**
     * The meta object literal for the '<em><b>Source State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_STATE__SOURCE_STATE = eINSTANCE.getEventState_SourceState();

    /**
     * The meta object literal for the '<em><b>Target State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_STATE__TARGET_STATE = eINSTANCE.getEventState_TargetState();

  }

} //ErrorModelPackage
