/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see hu.bme.mit.errorModel.ErrorModelPackage
 * @generated
 */
public interface ErrorModelFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ErrorModelFactory eINSTANCE = hu.bme.mit.errorModel.impl.ErrorModelFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Error Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Model</em>'.
   * @generated
   */
  ErrorModel createErrorModel();

  /**
   * Returns a new object of class '<em>EModel Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EModel Dec</em>'.
   * @generated
   */
  EModelDec createEModelDec();

  /**
   * Returns a new object of class '<em>EModel Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EModel Element</em>'.
   * @generated
   */
  EModelElement createEModelElement();

  /**
   * Returns a new object of class '<em>Outer Propagation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outer Propagation</em>'.
   * @generated
   */
  OuterPropagation createOuterPropagation();

  /**
   * Returns a new object of class '<em>In Prop Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>In Prop Dec</em>'.
   * @generated
   */
  InPropDec createInPropDec();

  /**
   * Returns a new object of class '<em>Out Prop Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Out Prop Dec</em>'.
   * @generated
   */
  OutPropDec createOutPropDec();

  /**
   * Returns a new object of class '<em>State Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Dec</em>'.
   * @generated
   */
  StateDec createStateDec();

  /**
   * Returns a new object of class '<em>Event Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Dec</em>'.
   * @generated
   */
  EventDec createEventDec();

  /**
   * Returns a new object of class '<em>Transition Feature Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition Feature Dec</em>'.
   * @generated
   */
  TransitionFeatureDec createTransitionFeatureDec();

  /**
   * Returns a new object of class '<em>Trigger Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger Dec</em>'.
   * @generated
   */
  TriggerDec createTriggerDec();

  /**
   * Returns a new object of class '<em>Action Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Dec</em>'.
   * @generated
   */
  ActionDec createActionDec();

  /**
   * Returns a new object of class '<em>Transition State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition State</em>'.
   * @generated
   */
  TransitionState createTransitionState();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ErrorModelPackage getErrorModelPackage();

} //ErrorModelFactory
