/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.errorModel.ErrorModelPackage#getEventFeature()
 * @model
 * @generated
 */
public interface EventFeature extends EObject
{
} // EventFeature
