/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.errorModel.EventDec#getEventFeatures <em>Event Features</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.errorModel.ErrorModelPackage#getEventDec()
 * @model
 * @generated
 */
public interface EventDec extends EModelElement
{
  /**
   * Returns the value of the '<em><b>Event Features</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.errorModel.EventFeature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Features</em>' containment reference list.
   * @see hu.bme.mit.errorModel.ErrorModelPackage#getEventDec_EventFeatures()
   * @model containment="true"
   * @generated
   */
  EList<EventFeature> getEventFeatures();

} // EventDec
