/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outer Propagation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.errorModel.ErrorModelPackage#getOuterPropagation()
 * @model
 * @generated
 */
public interface OuterPropagation extends EModelElement
{
} // OuterPropagation
