/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Out Prop Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.errorModel.OutPropDec#getFromState <em>From State</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.errorModel.ErrorModelPackage#getOutPropDec()
 * @model
 * @generated
 */
public interface OutPropDec extends OuterPropagation
{
  /**
   * Returns the value of the '<em><b>From State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From State</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From State</em>' reference.
   * @see #setFromState(EventDec)
   * @see hu.bme.mit.errorModel.ErrorModelPackage#getOutPropDec_FromState()
   * @model
   * @generated
   */
  EventDec getFromState();

  /**
   * Sets the value of the '{@link hu.bme.mit.errorModel.OutPropDec#getFromState <em>From State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From State</em>' reference.
   * @see #getFromState()
   * @generated
   */
  void setFromState(EventDec value);

} // OutPropDec
