/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel.impl;

import hu.bme.mit.componentModel.AbstractComponentFeatures;
import hu.bme.mit.componentModel.ComponentModelPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Component Features</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractComponentFeaturesImpl extends MinimalEObjectImpl.Container implements AbstractComponentFeatures
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractComponentFeaturesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComponentModelPackage.Literals.ABSTRACT_COMPONENT_FEATURES;
  }

} //AbstractComponentFeaturesImpl
