/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel.impl;

import hu.bme.mit.componentModel.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComponentModelFactoryImpl extends EFactoryImpl implements ComponentModelFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ComponentModelFactory init()
  {
    try
    {
      ComponentModelFactory theComponentModelFactory = (ComponentModelFactory)EPackage.Registry.INSTANCE.getEFactory(ComponentModelPackage.eNS_URI);
      if (theComponentModelFactory != null)
      {
        return theComponentModelFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ComponentModelFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentModelFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ComponentModelPackage.COMPONENT_MODEL: return createComponentModel();
      case ComponentModelPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case ComponentModelPackage.PORT_TYPE: return createPortType();
      case ComponentModelPackage.ERROR_MODES: return createErrorModes();
      case ComponentModelPackage.COMPONENT_MODEL_DEC: return createComponentModelDec();
      case ComponentModelPackage.SYSTEM_CONN_DEC: return createSystemConnDec();
      case ComponentModelPackage.SYSTEM_DEC: return createSystemDec();
      case ComponentModelPackage.ABSTRACT_FEATURES: return createAbstractFeatures();
      case ComponentModelPackage.SYSTEM_PORT_DEC: return createSystemPortDec();
      case ComponentModelPackage.SYSTEM_PORT_IN: return createSystemPortIn();
      case ComponentModelPackage.SYSTEM_PORT_OUT: return createSystemPortOut();
      case ComponentModelPackage.COMP_CONN_DEC: return createCompConnDec();
      case ComponentModelPackage.COMPONENT_IMPL: return createComponentImpl();
      case ComponentModelPackage.COMPONENT_TYPE: return createComponentType();
      case ComponentModelPackage.ABSTRACT_COMPONENT_FEATURES: return createAbstractComponentFeatures();
      case ComponentModelPackage.PORT: return createPort();
      case ComponentModelPackage.IN_PORT: return createInPort();
      case ComponentModelPackage.OUT_PORT: return createOutPort();
      case ComponentModelPackage.EMODEL_DEC: return createEModelDec();
      case ComponentModelPackage.EMODEL_ELEMENT: return createEModelElement();
      case ComponentModelPackage.STATE_DEC: return createStateDec();
      case ComponentModelPackage.TRANSITION_DEC: return createTransitionDec();
      case ComponentModelPackage.TRANSITION_FEATURE_DEC: return createTransitionFeatureDec();
      case ComponentModelPackage.TRANSITION_STATE: return createTransitionState();
      case ComponentModelPackage.TRIGGER_DEC: return createTriggerDec();
      case ComponentModelPackage.ACTION_DEC: return createActionDec();
      case ComponentModelPackage.OCCURRENCE_DEC: return createOccurrenceDec();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentModel createComponentModel()
  {
    ComponentModelImpl componentModel = new ComponentModelImpl();
    return componentModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PortType createPortType()
  {
    PortTypeImpl portType = new PortTypeImpl();
    return portType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ErrorModes createErrorModes()
  {
    ErrorModesImpl errorModes = new ErrorModesImpl();
    return errorModes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentModelDec createComponentModelDec()
  {
    ComponentModelDecImpl componentModelDec = new ComponentModelDecImpl();
    return componentModelDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemConnDec createSystemConnDec()
  {
    SystemConnDecImpl systemConnDec = new SystemConnDecImpl();
    return systemConnDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemDec createSystemDec()
  {
    SystemDecImpl systemDec = new SystemDecImpl();
    return systemDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractFeatures createAbstractFeatures()
  {
    AbstractFeaturesImpl abstractFeatures = new AbstractFeaturesImpl();
    return abstractFeatures;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemPortDec createSystemPortDec()
  {
    SystemPortDecImpl systemPortDec = new SystemPortDecImpl();
    return systemPortDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemPortIn createSystemPortIn()
  {
    SystemPortInImpl systemPortIn = new SystemPortInImpl();
    return systemPortIn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemPortOut createSystemPortOut()
  {
    SystemPortOutImpl systemPortOut = new SystemPortOutImpl();
    return systemPortOut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CompConnDec createCompConnDec()
  {
    CompConnDecImpl compConnDec = new CompConnDecImpl();
    return compConnDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentImpl createComponentImpl()
  {
    ComponentImplImpl componentImpl = new ComponentImplImpl();
    return componentImpl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentType createComponentType()
  {
    ComponentTypeImpl componentType = new ComponentTypeImpl();
    return componentType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractComponentFeatures createAbstractComponentFeatures()
  {
    AbstractComponentFeaturesImpl abstractComponentFeatures = new AbstractComponentFeaturesImpl();
    return abstractComponentFeatures;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Port createPort()
  {
    PortImpl port = new PortImpl();
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InPort createInPort()
  {
    InPortImpl inPort = new InPortImpl();
    return inPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OutPort createOutPort()
  {
    OutPortImpl outPort = new OutPortImpl();
    return outPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EModelDec createEModelDec()
  {
    EModelDecImpl eModelDec = new EModelDecImpl();
    return eModelDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EModelElement createEModelElement()
  {
    EModelElementImpl eModelElement = new EModelElementImpl();
    return eModelElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StateDec createStateDec()
  {
    StateDecImpl stateDec = new StateDecImpl();
    return stateDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TransitionDec createTransitionDec()
  {
    TransitionDecImpl transitionDec = new TransitionDecImpl();
    return transitionDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TransitionFeatureDec createTransitionFeatureDec()
  {
    TransitionFeatureDecImpl transitionFeatureDec = new TransitionFeatureDecImpl();
    return transitionFeatureDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TransitionState createTransitionState()
  {
    TransitionStateImpl transitionState = new TransitionStateImpl();
    return transitionState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TriggerDec createTriggerDec()
  {
    TriggerDecImpl triggerDec = new TriggerDecImpl();
    return triggerDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ActionDec createActionDec()
  {
    ActionDecImpl actionDec = new ActionDecImpl();
    return actionDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OccurrenceDec createOccurrenceDec()
  {
    OccurrenceDecImpl occurrenceDec = new OccurrenceDecImpl();
    return occurrenceDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentModelPackage getComponentModelPackage()
  {
    return (ComponentModelPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ComponentModelPackage getPackage()
  {
    return ComponentModelPackage.eINSTANCE;
  }

} //ComponentModelFactoryImpl
