/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.componentModel.impl;

import hu.bme.mit.componentModel.ComponentModelPackage;
import hu.bme.mit.componentModel.EModelDec;
import hu.bme.mit.componentModel.EModelElement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EModel Dec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.componentModel.impl.EModelDecImpl#getNameEModelDec <em>Name EModel Dec</em>}</li>
 *   <li>{@link hu.bme.mit.componentModel.impl.EModelDecImpl#getEmodelElements <em>Emodel Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EModelDecImpl extends AbstractComponentFeaturesImpl implements EModelDec
{
  /**
   * The default value of the '{@link #getNameEModelDec() <em>Name EModel Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameEModelDec()
   * @generated
   * @ordered
   */
  protected static final String NAME_EMODEL_DEC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameEModelDec() <em>Name EModel Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameEModelDec()
   * @generated
   * @ordered
   */
  protected String nameEModelDec = NAME_EMODEL_DEC_EDEFAULT;

  /**
   * The cached value of the '{@link #getEmodelElements() <em>Emodel Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmodelElements()
   * @generated
   * @ordered
   */
  protected EList<EModelElement> emodelElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EModelDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComponentModelPackage.Literals.EMODEL_DEC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNameEModelDec()
  {
    return nameEModelDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNameEModelDec(String newNameEModelDec)
  {
    String oldNameEModelDec = nameEModelDec;
    nameEModelDec = newNameEModelDec;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComponentModelPackage.EMODEL_DEC__NAME_EMODEL_DEC, oldNameEModelDec, nameEModelDec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EModelElement> getEmodelElements()
  {
    if (emodelElements == null)
    {
      emodelElements = new EObjectContainmentEList<EModelElement>(EModelElement.class, this, ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS);
    }
    return emodelElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS:
        return ((InternalEList<?>)getEmodelElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComponentModelPackage.EMODEL_DEC__NAME_EMODEL_DEC:
        return getNameEModelDec();
      case ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS:
        return getEmodelElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComponentModelPackage.EMODEL_DEC__NAME_EMODEL_DEC:
        setNameEModelDec((String)newValue);
        return;
      case ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS:
        getEmodelElements().clear();
        getEmodelElements().addAll((Collection<? extends EModelElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComponentModelPackage.EMODEL_DEC__NAME_EMODEL_DEC:
        setNameEModelDec(NAME_EMODEL_DEC_EDEFAULT);
        return;
      case ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS:
        getEmodelElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComponentModelPackage.EMODEL_DEC__NAME_EMODEL_DEC:
        return NAME_EMODEL_DEC_EDEFAULT == null ? nameEModelDec != null : !NAME_EMODEL_DEC_EDEFAULT.equals(nameEModelDec);
      case ComponentModelPackage.EMODEL_DEC__EMODEL_ELEMENTS:
        return emodelElements != null && !emodelElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nameEModelDec: ");
    result.append(nameEModelDec);
    result.append(')');
    return result.toString();
  }

} //EModelDecImpl
