/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel.impl;

import hu.bme.mit.errorModel.ErrorModelPackage;
import hu.bme.mit.errorModel.EventDec;
import hu.bme.mit.errorModel.InPropDec;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>In Prop Dec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.errorModel.impl.InPropDecImpl#getAffectedState <em>Affected State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InPropDecImpl extends OuterPropagationImpl implements InPropDec
{
  /**
   * The cached value of the '{@link #getAffectedState() <em>Affected State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAffectedState()
   * @generated
   * @ordered
   */
  protected EventDec affectedState;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InPropDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ErrorModelPackage.Literals.IN_PROP_DEC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EventDec getAffectedState()
  {
    if (affectedState != null && affectedState.eIsProxy())
    {
      InternalEObject oldAffectedState = (InternalEObject)affectedState;
      affectedState = (EventDec)eResolveProxy(oldAffectedState);
      if (affectedState != oldAffectedState)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE, oldAffectedState, affectedState));
      }
    }
    return affectedState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EventDec basicGetAffectedState()
  {
    return affectedState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAffectedState(EventDec newAffectedState)
  {
    EventDec oldAffectedState = affectedState;
    affectedState = newAffectedState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE, oldAffectedState, affectedState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE:
        if (resolve) return getAffectedState();
        return basicGetAffectedState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE:
        setAffectedState((EventDec)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE:
        setAffectedState((EventDec)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ErrorModelPackage.IN_PROP_DEC__AFFECTED_STATE:
        return affectedState != null;
    }
    return super.eIsSet(featureID);
  }

} //InPropDecImpl
