/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel.impl;

import hu.bme.mit.errorModel.ErrorModelPackage;
import hu.bme.mit.errorModel.OuterPropagation;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Outer Propagation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OuterPropagationImpl extends EModelElementImpl implements OuterPropagation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OuterPropagationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ErrorModelPackage.Literals.OUTER_PROPAGATION;
  }

} //OuterPropagationImpl
