/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.errorModel.impl;

import hu.bme.mit.errorModel.ErrorModelPackage;
import hu.bme.mit.errorModel.TransitionFeatureDec;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transition Feature Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TransitionFeatureDecImpl extends MinimalEObjectImpl.Container implements TransitionFeatureDec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransitionFeatureDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ErrorModelPackage.Literals.TRANSITION_FEATURE_DEC;
  }

} //TransitionFeatureDecImpl
